language: java
sudo: true
jdk:
  - openjdk8
before_install:
  - chmod +x travis-status.sh
  - chmod +x gradlew
  - git config --global user.email "travis@travis-ci.org" && git config --global user.name "Travis CI"
  - gpg2 --batch --cipher-algo AES256 --passphrase $SIGNING_KEYPASSWORD travis_secret_key.gpg
script:
  - ./gradlew clean build
  - if [[ $TRAVIS_COMMIT_MESSAGE == *"--snapshot"* ]]; then ./gradlew publish > /dev/null; fi ;
  - if [[ $TRAVIS_COMMIT_MESSAGE == *"--release"* && $TRAVIS_BRANCH == *"master"* ]]; then ./gradlew clean publishToNexus > /dev/null; fi ;
  - if [[ $TRAVIS_COMMIT_MESSAGE == *"--release"* && $TRAVIS_BRANCH == *"master"* ]]; then ./gradlew closeAndReleaseRepository; fi ;
  - if [[ $TRAVIS_BRANCH == *"master"* ]]; then rm -rf docs/build && rm -rf docs/apidocs; fi ;
  - if [[ $TRAVIS_BRANCH == *"master"* ]]; then ./gradlew generateJavaDocPages > /dev/null; fi ;
  - if [[ $TRAVIS_BRANCH == *"master"* ]]; then git add docs && git commit --message "Travis build $TRAVIS_BUILD_NUMBER [skip travis-ci]"; fi ;
  - if [[ $TRAVIS_BRANCH == *"master"* ]]; then git push --quiet https://Shynixn:$GH_TOKEN@github.com/Shynixn/MCCoroutine.git HEAD:master; fi ;
after_success:
  - ./gradlew jacocoRootReport
  - bash <(curl -s https://codecov.io/bash)
  - ./travis-status.sh success $DISCORD_TOKEN
after_failure:
  - ./travis-status.sh failure $DISCORD_TOKEN
